version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server --appendonly yes --save 900 1 --save 300 10 --save 60 10000
